# Site settings
markdown: rdiscount
highlighter: pygments
exclude: ['README.md', 'src/', 'node_modules', 'package.json', 'gulpfile.js']
permalink: /:year/:month/:title
paginate: 10
enforce_ssl: www.buttenschoen.ca
url: https://www.buttenschoen.ca
